### ISSUE TITLE
Account Support

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-3-#152]
The system should support accounts with access locking of activities.

**Comment by JuHardtung** [comment]
I need help to clarify certain conditions for our account system.

- if we want to offer the fieldbook for full offline use, then the user obviously can't log in to his account
- but with offline use we can't sync data to the backend server
- and if we just offer syncing once an internet connection has been established, every user could view and edit all activities that where ever created
- and how about multiple users that want to work on the same activity, place, or position?

So how should we handle this?

Should we just offer the account system, if they want to use the "cloud backup" features and syncing of information on one activity by multiple users?
Otherwise, the whole system would just work locally.

But if we follow this approach, then we need to change the current version of the landing page, because it "forces" the user to sign-up/login before being able to use the system.

**Comment by Me0li** [comment]
I think the following points should be able to solve the problem:

**Offline Mode:**
The landing page shows no login or signup option. The user simply clicks a “get started” button or something similar and can start working straight away. Login and signup disappear into the sidebar and can be used again as soon as the system is online again.

**Online and Offline Mode:**
- We should provide an account management option in the sidebar that allows profile information such as username, email (etc.).
- We should also offer a synchronization button that can only be clicked when the system is online
- In principle, it should be enough to save data offline. Synchronization should not be forced

**Online Mode:**
- An excavation manager creates a project and adds employees (editors), this reduces synchronization problems
- (Excavation manager sees all activities - employees only see the activity to which they were added)
- (currently processed positions could be locked for other editors so that no one else can work on the same position at the same time)

**Nice to have:**
(Settings such as theme and language are saved via account)

**Comment by Methusshan25** [comment]
Just an idea. Lets add the account management option button into the pathbar. So the current Account is always visible. The button could be an profile picture, similar as in GitHub or YouTube. A click opens a menu with the option to logout or change the account. And an option to change the account data.

**Comment by JuHardtung** [comment]
General Account support was added with 1286afcf2db3892297fc36bd674a3a2e2ab32b5c, but we still need to rework the frontent UI for this.
