### ISSUE TITLE
Selection of position does not persist when entering the 3D-Part

### ISSUE THREAD

**Issue by TMink** [TMink/Digitales-3D-Feldbuch-Projekt-3-#175]
When switching to the 3D-Part, the position selection is deleted. Probaly an cookie related issue.

**Comment by JuHardtung** [comment]
The issue occurred due to these lines within the `created()`-function of the `Navigation.vue`.

![Code_3crZscLfr5](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/bcf0a2d0-605e-4706-b449-092566202a81)


We originally implemented this logic, because the user has only actively chosen a specific position while editing it. Once the user returns to the `PositionOverview`, the user has technically not chosen a specific position anymore.

Although this logically makes sense, we shouldn't just remove this cookie.

Firstly, this would be confusing for the user.
Secondly, this creates issues for the 3d-View workflow (as outlined in this issue)
Thirdly, if you think about the cookie as 'last chosen position' this still makes sense.
